import Logo from "../components/Logo";
import Head from "next/head";
import Login from '../components/Login';
import styles from '../styles/Header.module.css';
import Main from '../styles/Main.module.css';
import Image from "next/image";


export default function Home() {
  return (
    <>
      <Head>
        <title>Register&Stock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header className={styles.headerContainer}>
        <div className="header-logo">
          <Logo />
        </div>
        <div className="header-login">
          <Login />
        </div>
      </header>
      <main className={Main.mainContainer}>
      <h1>Resgister & Stock</h1>
        <Image 
          src="/img/logoImage.png"
          width={645}
          height={387}
          alt="Logo da HomePage"
        />
      </main>
    </>
  );
}
